In [34]:
import pandas as pd
import numpy as np
data = pd.read_csv(r'Investment_Data_Train.xlsx - train_data.csv', index_col = 0)

In [35]:
data.isna()
data.dropna(inplace = True)
data_1 = data.set_index("MSN")
data_new = data_1.iloc[:,1:]
data_new

,Year,Amount,State,CO2 Emissions (Mmt),TotalNumberofInvestments,TotalAmountofAssistance
MSN,,,,,,
BDFDB,2015,21.0,Alaska,35.027804,16.0,3345612.0
BDPRP,2015,4.0,Alaska,35.027804,16.0,3345612.0
BFFDB,2015,21.0,Alaska,35.027804,16.0,3345612.0
BFPRP,2015,4.0,Alaska,35.027804,16.0,3345612.0
CLPRB,2015,17747.0,Alaska,35.027804,16.0,3345612.0
...,...,...,...,...,...,...
WDPRB,2019,4969.0,Wyoming,59.096649,32.0,570570.0
WDTCB,2019,4969.0,Wyoming,59.096649,32.0,570570.0
WSTCB,2019,0.0,Wyoming,59.096649,32.0,570570.0
WWPRB,2019,4969.0,Wyoming,59.096649,32.0,570570.0
WYTCB,2019,37070.0,Wyoming,59.096649,32.0,570570.0

In [36]:
data_sub = data_new.iloc[:29,:]
data_sub2 = data_sub.transpose()
data_sub2

MSN,BDFDB,BDPRP,BFFDB,BFPRP,CLPRB,CLPRK,CLPRP,COPRK,EMFDB,ENPRP,...,REPRB,SOTCB,TEPRB,TETCB,WDEXB,WDPRB,WDTCB,WSTCB,WWPRB,WYTCB
Year,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015,...,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015
Amount,21.0,4.0,21.0,4.0,17747.0,15.073,1177.0,5.717,0.0,0.0,...,23807.0,3.0,1429942.0,614242.0,0.0,6865.0,6865.0,622.0,7488.0,1488.0
State,Alaska,Alaska,Alaska,Alaska,Alaska,Alaska,Alaska,Alaska,Alaska,Alaska,...,Alaska,Alaska,Alaska,Alaska,Alaska,Alaska,Alaska,Alaska,Alaska,Alaska
CO2 Emissions (Mmt),35.027804,35.027804,35.027804,35.027804,35.027804,35.027804,35.027804,35.027804,35.027804,35.027804,...,35.027804,35.027804,35.027804,35.027804,35.027804,35.027804,35.027804,35.027804,35.027804,35.027804
TotalNumberofInvestments,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,...,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0
TotalAmountofAssistance,3345612.0,3345612.0,3345612.0,3345612.0,3345612.0,3345612.0,3345612.0,3345612.0,3345612.0,3345612.0,...,3345612.0,3345612.0,3345612.0,3345612.0,3345612.0,3345612.0,3345612.0,3345612.0,3345612.0,3345612.0

In [37]:
df = pd.DataFrame()
for place in set(data_new['State']):
    for time in set(data_new['Year']):
        data_sub = data_new.loc[(data_new.State == place) & (data_new.Year == time)]
        data_sub2 = data_sub.transpose()
        data_sub3 = data_sub2.loc['Amount',:]
        df = pd.concat([df,data_sub3], axis = 1)
df

,Amount,Amount,Amount,Amount,Amount,Amount,Amount,Amount,Amount,Amount,...,Amount,Amount,Amount,Amount,Amount,Amount,Amount,Amount,Amount,Amount
BDFDB,27.0,29.0,15.0,0.0,21.0,9572.0,8987.0,9775.0,9191.0,7761.0,...,18598.0,17714.0,18333.0,17366.0,19087.0,0.0,0.0,0.0,0.0,0.0
BDPRP,5.0,5.0,3.0,0.0,4.0,1762.0,1654.0,1799.0,1692.0,1429.0,...,3423.0,3260.0,3374.0,3196.0,3513.0,0.0,0.0,0.0,0.0,0.0
BFFDB,27.0,29.0,15.0,0.0,21.0,168756.0,171550.0,176402.0,180685.0,165989.0,...,252801.0,243223.0,226419.0,218212.0,230655.0,0.0,0.0,0.0,0.0,0.0
BFPRP,5.0,5.0,3.0,0.0,4.0,29682.0,30163.0,30986.0,31799.0,29147.0,...,44501.0,42808.0,39823.0,38456.0,40575.0,0.0,0.0,0.0,0.0,0.0
CLPRB,13942.0,14365.0,13752.0,14867.0,17747.0,0.0,0.0,0.0,0.0,0.0,...,977131.0,1079624.0,1095887.0,1014448.0,1252879.0,37859.0,42804.0,30464.0,34661.0,45587.0
CLPRK,14.957,14.978,15.253,15.252,15.073,0.0,0.0,0.0,0.0,0.0,...,22.424,22.351,22.147,22.103,22.282,23.431,23.67,23.468,23.562,23.72
CLPRP,932.0,959.0,902.0,975.0,1177.0,0.0,0.0,0.0,0.0,0.0,...,43575.0,48303.0,49482.0,45895.0,56227.0,1616.0,1808.0,1298.0,1471.0,1922.0
COPRK,5.722,5.723,5.706,5.698,5.717,0.0,0.0,0.0,0.0,0.0,...,5.722,5.723,5.706,5.698,5.717,0.0,0.0,0.0,0.0,0.0
EMFDB,0.0,0.0,0.0,0.0,0.0,159184.0,162563.0,166627.0,171494.0,158228.0,...,234203.0,225509.0,208086.0,200846.0,211568.0,0.0,0.0,0.0,0.0,0.0
ENPRP,0.0,0.0,0.0,0.0,0.0,27920.0,28509.0,29187.0,30107.0,27718.0,...,41078.0,39548.0,36449.0,35260.0,37062.0,0.0,0.0,0.0,0.0,0.0
GETCB,186.0,186.0,186.0,186.0,186.0,1075.0,1075.0,1075.0,1075.0,1075.0,...,2042.0,2042.0,2042.0,2042.0,2042.0,570.0,570.0,570.0,570.0,570.0
HYTCB,15317.0,15143.0,15151.0,14456.0,14621.0,11157.0,11587.0,9591.0,9404.0,7912.0,...,1226.0,1153.0,1334.0,1103.0,1160.0,12853.0,18108.0,25772.0,19485.0,15127.0
NCPRB,17081.0,16655.0,16777.0,15951.0,16298.0,104583.0,121517.0,118640.0,120386.0,100589.0,...,103746.0,118502.0,114443.0,135410.0,105293.0,25123.0,33197.0,42987.0,37802.0,24122.0
NGMPB,369865.0,382940.0,375279.0,364363.0,380887.0,0.0,0.0,0.0,0.0,0.0,...,2317.0,2260.0,2596.0,2279.0,2210.0,36.0,34.0,14.0,14.0,40.0
NGMPK,1.112,1.112,1.1,1.106,1.108,0.0,0.0,0.0,0.0,0.0,...,1.061,1.06,1.054,1.06,1.062,1.051,1.047,1.042,1.044,1.055
NGMPP,332749.0,344385.0,341315.0,329361.0,343625.0,0.0,0.0,0.0,0.0,0.0,...,2183.0,2131.0,2464.0,2150.0,2080.0,34.0,32.0,13.0,13.0,38.0
NUETB,0.0,0.0,0.0,0.0,0.0,144970.0,145426.0,152657.0,147280.0,125900.0,...,1031331.0,1016522.0,1025651.0,1030996.0,1017377.0,154377.0,158004.0,156699.0,156765.0,153140.0
PAPRB,1026401.0,1033270.0,997415.0,968358.0,1007501.0,0.0,0.0,0.0,0.0,0.0,...,49432.0,47581.0,48045.0,46969.0,54426.0,0.0,0.0,0.0,0.0,0.0
PAPRP,179378.0,180547.0,174801.0,169947.0,176229.0,0.0,0.0,0.0,0.0,0.0,...,8639.0,8314.0,8420.0,8243.0,9520.0,0.0,0.0,0.0,0.0,0.0
REPRB,25155.0,23620.0,24158.0,22754.0,23807.0,351303.0,363504.0,366439.0,366164.0,345949.0,...,375139.0,378606.0,359817.0,372731.0,355359.0,48237.0,55339.0,65963.0,55557.0,47614.0
SOTCB,14.0,20.0,28.0,40.0,3.0,645.0,6247.0,10437.0,12265.0,473.0,...,2033.0,2285.0,2739.0,3503.0,1938.0,6834.0,9348.0,11456.0,13115.0,4375.0
TEPRB,1435363.0,1454196.0,1410604.0,1370342.0,1429942.0,496273.0,508930.0,519096.0,513444.0,471848.0,...,2435349.0,2524593.0,2531996.0,2467422.0,2682250.0,240509.0,256180.0,253139.0,246996.0,246381.0
TETCB,593662.0,601492.0,604644.0,605689.0,614242.0,1838918.0,1862210.0,1940174.0,1900531.0,1813635.0,...,3925630.0,3890442.0,4017644.0,3951620.0,3920125.0,1386648.0,1346703.0,1391698.0,1355227.0,1424201.0
WDEXB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
WDPRB,7636.0,6501.0,6910.0,6418.0,6865.0,63244.0,56284.0,58812.0,56250.0,65241.0,...,7597.0,7430.0,8890.0,9268.0,8185.0,14188.0,12954.0,14204.0,10199.0,14425.0
WDTCB,7636.0,6501.0,6910.0,6418.0,6865.0,63244.0,56284.0,58812.0,56250.0,65241.0,...,7597.0,7430.0,8890.0,9268.0,8185.0,14188.0,12954.0,14204.0,10199.0,14425.0
WSTCB,412.0,436.0,456.0,386.0,622.0,14720.0,14153.0,12585.0,8843.0,14129.0,...,10995.0,9450.0,10065.0,9841.0,11225.0,8927.0,9188.0,8772.0,7556.0,9067.0
WWPRB,8048.0,6937.0,7366.0,6803.0,7488.0,77964.0,70437.0,71397.0,65093.0,79370.0,...,18592.0,16880.0,18955.0,19109.0,19411.0,23115.0,22142.0,22975.0,17755.0,23492.0
WYTCB,1563.0,1305.0,1411.0,1270.0,1488.0,91706.0,102608.0,97537.0,97642.0,91129.0,...,98445.0,113023.0,108328.0,128763.0,100154.0,4866.0,5172.0,5189.0,4633.0,4050.0

In [68]:
df = pd.DataFrame()
state_df = pd.DataFrame()
for place in set(data_new['State']):
    state = {'State': place}
#     print(state)
    for time in set(data_new['Year']):
        data_sub = data_new.loc[(data_new.State == place) & (data_new.Year == time)]
        data_sub2 = data_sub.transpose()
        data_sub3 = data_sub2.loc['Amount',:]
        df = pd.concat([df,data_sub3], axis = 1)
        state_df = state_df.append(state, ignore_index = True)
        #print(state_df)
df = df.transpose()
df.index = [i for i in range(250)]
df = pd.concat([df, state_df],axis=1)

In [80]:
df = pd.DataFrame()
state_df = pd.DataFrame()
co2_df = pd.DataFrame()
for place in set(data_new['State']):
    state = {'State': place}
    co2 = {'CO2': data_new[data_new['State']==place]['CO2 Emissions (Mmt)'][0]}
    for time in set(data_new['Year']):
        data_sub = data_new.loc[(data_new.State == place) & (data_new.Year == time)]
        data_sub2 = data_sub.transpose()
        data_sub3 = data_sub2.loc['Amount',:]
        df = pd.concat([df,data_sub3], axis = 1)
        state_df = state_df.append(state, ignore_index = True)
        co2_df = co2_df.append(co2, ignore_index = True)
        #print(state_df)
df = df.transpose()
df.index = [i for i in range(250)]
df = pd.concat([df, state_df],axis=1)
df = pd.concat([df, co2_df],axis=1)

In [82]:
df

,BDFDB,BDPRP,BFFDB,BFPRP,CLPRB,CLPRK,CLPRP,COPRK,EMFDB,ENPRP,...,TEPRB,TETCB,WDEXB,WDPRB,WDTCB,WSTCB,WWPRB,WYTCB,State,CO2
0,27.0,5.0,27.0,5.0,13942.0,14.957,932.0,5.722,0.0,0.0,...,1435363.0,593662.0,0.0,7636.0,7636.0,412.0,8048.0,1563.0,Alaska,35.027804
1,29.0,5.0,29.0,5.0,14365.0,14.978,959.0,5.723,0.0,0.0,...,1454196.0,601492.0,0.0,6501.0,6501.0,436.0,6937.0,1305.0,Alaska,35.027804
2,15.0,3.0,15.0,3.0,13752.0,15.253,902.0,5.706,0.0,0.0,...,1410604.0,604644.0,0.0,6910.0,6910.0,456.0,7366.0,1411.0,Alaska,35.027804
3,0.0,0.0,0.0,0.0,14867.0,15.252,975.0,5.698,0.0,0.0,...,1370342.0,605689.0,0.0,6418.0,6418.0,386.0,6803.0,1270.0,Alaska,35.027804
4,21.0,4.0,21.0,4.0,17747.0,15.073,1177.0,5.717,0.0,0.0,...,1429942.0,614242.0,0.0,6865.0,6865.0,622.0,7488.0,1488.0,Alaska,35.027804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,0.0,0.0,0.0,0.0,37859.0,23.431,1616.0,0.0,0.0,0.0,...,240509.0,1386648.0,0.0,14188.0,14188.0,8927.0,23115.0,4866.0,Maryland,62.280327
246,0.0,0.0,0.0,0.0,42804.0,23.67,1808.0,0.0,0.0,0.0,...,256180.0,1346703.0,0.0,12954.0,12954.0,9188.0,22142.0,5172.0,Maryland,62.280327
247,0.0,0.0,0.0,0.0,30464.0,23.468,1298.0,0.0,0.0,0.0,...,253139.0,1391698.0,0.0,14204.0,14204.0,8772.0,22975.0,5189.0,Maryland,62.280327
248,0.0,0.0,0.0,0.0,34661.0,23.562,1471.0,0.0,0.0,0.0,...,246996.0,1355227.0,0.0,10199.0,10199.0,7556.0,17755.0,4633.0,Maryland,62.280327
249,0.0,0.0,0.0,0.0,45587.0,23.72,1922.0,0.0,0.0,0.0,...,246381.0,1424201.0,0.0,14425.0,14425.0,9067.0,23492.0,4050.0,Maryland,62.280327

,BDFDB,BDPRP,BFFDB,BFPRP,CLPRB,CLPRK,CLPRP,COPRK,EMFDB,ENPRP,...,SOTCB,TEPRB,TETCB,WDEXB,WDPRB,WDTCB,WSTCB,WWPRB,WYTCB,State
0,27.0,5.0,27.0,5.0,13942.0,14.957,932.0,5.722,0.0,0.0,...,14.0,1435363.0,593662.0,0.0,7636.0,7636.0,412.0,8048.0,1563.0,Alaska
1,29.0,5.0,29.0,5.0,14365.0,14.978,959.0,5.723,0.0,0.0,...,20.0,1454196.0,601492.0,0.0,6501.0,6501.0,436.0,6937.0,1305.0,Alaska
2,15.0,3.0,15.0,3.0,13752.0,15.253,902.0,5.706,0.0,0.0,...,28.0,1410604.0,604644.0,0.0,6910.0,6910.0,456.0,7366.0,1411.0,Alaska
3,0.0,0.0,0.0,0.0,14867.0,15.252,975.0,5.698,0.0,0.0,...,40.0,1370342.0,605689.0,0.0,6418.0,6418.0,386.0,6803.0,1270.0,Alaska
4,21.0,4.0,21.0,4.0,17747.0,15.073,1177.0,5.717,0.0,0.0,...,3.0,1429942.0,614242.0,0.0,6865.0,6865.0,622.0,7488.0,1488.0,Alaska
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,0.0,0.0,0.0,0.0,37859.0,23.431,1616.0,0.0,0.0,0.0,...,6834.0,240509.0,1386648.0,0.0,14188.0,14188.0,8927.0,23115.0,4866.0,Maryland
246,0.0,0.0,0.0,0.0,42804.0,23.67,1808.0,0.0,0.0,0.0,...,9348.0,256180.0,1346703.0,0.0,12954.0,12954.0,9188.0,22142.0,5172.0,Maryland
247,0.0,0.0,0.0,0.0,30464.0,23.468,1298.0,0.0,0.0,0.0,...,11456.0,253139.0,1391698.0,0.0,14204.0,14204.0,8772.0,22975.0,5189.0,Maryland
248,0.0,0.0,0.0,0.0,34661.0,23.562,1471.0,0.0,0.0,0.0,...,13115.0,246996.0,1355227.0,0.0,10199.0,10199.0,7556.0,17755.0,4633.0,Maryland
249,0.0,0.0,0.0,0.0,45587.0,23.72,1922.0,0.0,0.0,0.0,...,4375.0,246381.0,1424201.0,0.0,14425.0,14425.0,9067.0,23492.0,4050.0,Maryland