In [78]:
%%html
<style type='text/css'>
.CodeMirror{
font-family: 'JetBrainsMono';
</style>

In [2]:
import pandas as pd

data = {'year': [2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016],
        'month': [12,11,10,9,8,7,6,5,4,3,2,1,12,11,10,9,8,7,6,5,4,3,2,1],
        'interest_rate': [2.75,2.5,2.5,2.5,2.5,2.5,2.5,2.25,2.25,2.25,2,2,2,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75],
        'unemployment_rate': [5.3,5.3,5.3,5.3,5.4,5.6,5.5,5.5,5.5,5.6,5.7,5.9,6,5.9,5.8,6.1,6.2,6.1,6.1,6.1,5.9,6.2,6.2,6.1],
        'index_price': [1464,1394,1357,1293,1256,1254,1234,1195,1159,1167,1130,1075,1047,965,943,958,971,949,884,866,876,822,704,719]        
        }
df = pd.DataFrame(data) 

print(df)

    year  month  interest_rate  unemployment_rate  index_price
0   2017     12           2.75                5.3         1464
1   2017     11           2.50                5.3         1394
2   2017     10           2.50                5.3         1357
3   2017      9           2.50                5.3         1293
4   2017      8           2.50                5.4         1256
5   2017      7           2.50                5.6         1254
6   2017      6           2.50                5.5         1234
7   2017      5           2.25                5.5         1195
8   2017      4           2.25                5.5         1159
9   2017      3           2.25                5.6         1167
10  2017      2           2.00                5.7         1130
11  2017      1           2.00                5.9         1075
12  2016     12           2.00                6.0         1047
13  2016     11           1.75                5.9          965
14  2016     10           1.75                5.8          943
15  2016      9           1.75                6.1          958
16  2016      8           1.75                6.2          971
17  2016      7           1.75                6.1          949
18  2016      6           1.75                6.1          884
19  2016      5           1.75                6.1          866
20  2016      4           1.75                5.9          876
21  2016      3           1.75                6.2          822
22  2016      2           1.75                6.2          704
23  2016      1           1.75                6.1          719

In [3]:
import pandas as pd
from sklearn import linear_model

df = pd.DataFrame(data)

x = df[['interest_rate','unemployment_rate']]
y = df['index_price']

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(19, 2) (19,)
(5, 2) (5,)

In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(mean_squared_error(y_test, y_pred)) 
print(model.coef_) #权重
print(model.n_features_in_) #几个输入

8739.922557984697
[ 325.99140793 -276.31517282]
2

In [6]:
## svr model
from sklearn.svm import SVR
model = SVR(kernel='rbf', gamma='auto')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(mean_squared_error(y_test, y_pred)) 
#print(model.coef_) #权重
print(model.n_features_in_) #几个输入

56006.84443036958
2

In [7]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor(random_state = 0)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(mean_squared_error(y_test, y_pred)) 
#print(model.coef_) #权重
print(model.n_features_in_) #几个输入

18978.211111111115
2

In [8]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators = 300, random_state = 0)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(mean_squared_error(y_test, y_pred)) 
#print(model.coef_) #权重
print(model.n_features_in_) #几个输入

16856.9490104294
2

In [9]:
### in case we want to take state into account...

# one hot encoder
df_invest = pd.read_csv('Investment_Data_Train.xlsx - train_data.csv')
new_df = pd.get_dummies(df_invest)

In [10]:
from sklearn.linear_model import Ridge
model = Ridge(alpha=.5)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(mean_squared_error(y_test, y_pred)) 
print(model.coef_) #权重
print(model.n_features_in_) #几个输入

9121.199419446895
[ 282.39928273 -248.6436158 ]
2

In [11]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(mean_squared_error(y_test, y_pred)) 
#print(model.coef_) #权重
print(model.n_features_in_) #几个输入

18959.476615697215
2

In [12]:
from sklearn.linear_model import Lasso
model = Lasso()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(mean_squared_error(y_test, y_pred)) 
print(model.coef_) #权重
print(model.n_features_in_) #几个输入

8685.389592438218
[ 326.13924645 -265.27410924]
2

In [13]:
from sklearn.linear_model import SGDRegressor
model = SGDRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(mean_squared_error(y_test, y_pred)) 
print(model.coef_) #权重
print(model.n_features_in_) #几个输入

9506.735500422375
[496.22528141  -3.30813882]
2

In [14]:
# other regressors we may want to try

# https://scikit-learn.org/stable/modules/classes.html#module-sklearn.linear_model
# https://scikit-learn.org/stable/modules/classes.html#module-sklearn.ensemble
# https://scikit-learn.org/stable/modules/classes.html#module-sklearn.tree

In [15]:
# Optional, if you want to eliminate unwanted features
# https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html#sklearn.feature_selection.RFE

In [16]:
# keras neural network with multi inputs

import keras
# https://stackoverflow.com/questions/65980952/python-could-not-install-packages-due-to-an-oserror-errno-2-no-such-file-or

In [30]:
import numpy as np
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras import layers
import tensorflow as tf

In [31]:
#https://www.tensorflow.org/tutorials/keras/regression?hl=zh-cn
def build_model():
    model = keras.Sequential([
        layers.Dense(64, activation='relu', input_shape=[len(X_train.keys())]),
        layers.Dense(64, activation='relu'),
        layers.Dense(1)
  ])

    optimizer = tf.keras.optimizers.RMSprop(0.001)

    model.compile(loss='mse',
        optimizer=optimizer,
        metrics=['mae', 'mse'])
    return model

In [32]:
model = build_model()

In [33]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 64)                192

 dense_7 (Dense)             (None, 64)                4160

 dense_8 (Dense)             (None, 1)                 65

=================================================================
Total params: 4,417
Trainable params: 4,417
Non-trainable params: 0
_________________________________________________________________

In [34]:
EPOCHS = 100
model.fit(
    X_train, y_train,
    epochs=EPOCHS, validation_split = 0.2, verbose=1)

Epoch 1/100
1/1 [==============================] - 1s 546ms/step - loss: 1287075.5000 - mae: 1119.7422 - mse: 1287075.5000 - val_loss: 874347.5625 - val_mae: 920.0472 - val_mse: 874347.5625
Epoch 2/100
1/1 [==============================] - 0s 22ms/step - loss: 1285812.5000 - mae: 1119.1754 - mse: 1285812.5000 - val_loss: 873529.7500 - val_mae: 919.6006 - val_mse: 873529.7500
Epoch 3/100
1/1 [==============================] - 0s 22ms/step - loss: 1284845.5000 - mae: 1118.7416 - mse: 1284845.5000 - val_loss: 872823.5000 - val_mae: 919.2150 - val_mse: 872823.5000
Epoch 4/100
1/1 [==============================] - 0s 21ms/step - loss: 1284010.1250 - mae: 1118.3668 - mse: 1284010.1250 - val_loss: 872173.0000 - val_mae: 918.8600 - val_mse: 872173.0000
Epoch 5/100
1/1 [==============================] - 0s 23ms/step - loss: 1283242.8750 - mae: 1118.0227 - mse: 1283242.8750 - val_loss: 871561.5000 - val_mae: 918.5261 - val_mse: 871561.5000
Epoch 6/100
1/1 [==============================] - 0s 21ms/step - loss: 1282520.6250 - mae: 1117.6987 - mse: 1282520.6250 - val_loss: 870974.6250 - val_mae: 918.2056 - val_mse: 870974.6250
Epoch 7/100
1/1 [==============================] - 0s 22ms/step - loss: 1281824.0000 - mae: 1117.3862 - mse: 1281824.0000 - val_loss: 870399.6250 - val_mae: 917.8914 - val_mse: 870399.6250
Epoch 8/100
1/1 [==============================] - 0s 22ms/step - loss: 1281140.5000 - mae: 1117.0797 - mse: 1281140.5000 - val_loss: 869838.3750 - val_mae: 917.5851 - val_mse: 869838.3750
Epoch 9/100
1/1 [==============================] - 0s 22ms/step - loss: 1280467.7500 - mae: 1116.7780 - mse: 1280467.7500 - val_loss: 869285.3750 - val_mae: 917.2833 - val_mse: 869285.3750
Epoch 10/100
1/1 [==============================] - 0s 22ms/step - loss: 1279803.7500 - mae: 1116.4805 - mse: 1279803.7500 - val_loss: 868734.9375 - val_mae: 916.9827 - val_mse: 868734.9375
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1279141.7500 - mae: 1116.1838 - mse: 1279141.7500 - val_loss: 868180.4375 - val_mae: 916.6797 - val_mse: 868180.4375
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1278477.7500 - mae: 1115.8861 - mse: 1278477.7500 - val_loss: 867626.2500 - val_mae: 916.3766 - val_mse: 867626.2500
Epoch 13/100
1/1 [==============================] - 0s 22ms/step - loss: 1277812.8750 - mae: 1115.5879 - mse: 1277812.8750 - val_loss: 867070.1250 - val_mae: 916.0724 - val_mse: 867070.1250
Epoch 14/100
1/1 [==============================] - 0s 27ms/step - loss: 1277145.6250 - mae: 1115.2885 - mse: 1277145.6250 - val_loss: 866509.3750 - val_mae: 915.7655 - val_mse: 866509.3750
Epoch 15/100
1/1 [==============================] - 0s 23ms/step - loss: 1276475.2500 - mae: 1114.9874 - mse: 1276475.2500 - val_loss: 865946.5625 - val_mae: 915.4575 - val_mse: 865946.5625
Epoch 16/100
1/1 [==============================] - 0s 23ms/step - loss: 1275799.2500 - mae: 1114.6840 - mse: 1275799.2500 - val_loss: 865386.5000 - val_mae: 915.1512 - val_mse: 865386.5000
Epoch 17/100
1/1 [==============================] - 0s 24ms/step - loss: 1275124.8750 - mae: 1114.3815 - mse: 1275124.8750 - val_loss: 864824.2500 - val_mae: 914.8433 - val_mse: 864824.2500
Epoch 18/100
1/1 [==============================] - 0s 23ms/step - loss: 1274449.3750 - mae: 1114.0780 - mse: 1274449.3750 - val_loss: 864258.2500 - val_mae: 914.5333 - val_mse: 864258.2500
Epoch 19/100
1/1 [==============================] - 0s 22ms/step - loss: 1273771.7500 - mae: 1113.7734 - mse: 1273771.7500 - val_loss: 863688.7500 - val_mae: 914.2213 - val_mse: 863688.7500
Epoch 20/100
1/1 [==============================] - 0s 23ms/step - loss: 1273090.6250 - mae: 1113.4672 - mse: 1273090.6250 - val_loss: 863125.8750 - val_mae: 913.9131 - val_mse: 863125.8750
Epoch 21/100
1/1 [==============================] - 0s 21ms/step - loss: 1272411.2500 - mae: 1113.1622 - mse: 1272411.2500 - val_loss: 862565.2500 - val_mae: 913.6055 - val_mse: 862565.2500
Epoch 22/100
1/1 [==============================] - 0s 22ms/step - loss: 1271737.8750 - mae: 1112.8594 - mse: 1271737.8750 - val_loss: 861998.0000 - val_mae: 913.2941 - val_mse: 861998.0000
Epoch 23/100
1/1 [==============================] - 0s 23ms/step - loss: 1271058.3750 - mae: 1112.5536 - mse: 1271058.3750 - val_loss: 861423.0000 - val_mae: 912.9783 - val_mse: 861423.0000
Epoch 24/100
1/1 [==============================] - 0s 22ms/step - loss: 1270370.7500 - mae: 1112.2441 - mse: 1270370.7500 - val_loss: 860841.0000 - val_mae: 912.6586 - val_mse: 860841.0000
Epoch 25/100
1/1 [==============================] - 0s 22ms/step - loss: 1269674.7500 - mae: 1111.9308 - mse: 1269674.7500 - val_loss: 860251.5000 - val_mae: 912.3348 - val_mse: 860251.5000
Epoch 26/100
1/1 [==============================] - 0s 23ms/step - loss: 1268969.6250 - mae: 1111.6132 - mse: 1268969.6250 - val_loss: 859655.1250 - val_mae: 912.0071 - val_mse: 859655.1250
Epoch 27/100
1/1 [==============================] - 0s 23ms/step - loss: 1268254.8750 - mae: 1111.2913 - mse: 1268254.8750 - val_loss: 859050.3750 - val_mae: 911.6747 - val_mse: 859050.3750
Epoch 28/100
1/1 [==============================] - 0s 23ms/step - loss: 1267529.8750 - mae: 1110.9647 - mse: 1267529.8750 - val_loss: 858437.2500 - val_mae: 911.3376 - val_mse: 858437.2500
Epoch 29/100
1/1 [==============================] - 0s 23ms/step - loss: 1266793.8750 - mae: 1110.6332 - mse: 1266793.8750 - val_loss: 857818.5000 - val_mae: 910.9975 - val_mse: 857818.5000
Epoch 30/100
1/1 [==============================] - 0s 23ms/step - loss: 1266048.8750 - mae: 1110.2975 - mse: 1266048.8750 - val_loss: 857195.0000 - val_mae: 910.6545 - val_mse: 857195.0000
Epoch 31/100
1/1 [==============================] - 0s 23ms/step - loss: 1265299.2500 - mae: 1109.9596 - mse: 1265299.2500 - val_loss: 856563.0625 - val_mae: 910.3068 - val_mse: 856563.0625
Epoch 32/100
1/1 [==============================] - 0s 24ms/step - loss: 1264540.3750 - mae: 1109.6174 - mse: 1264540.3750 - val_loss: 855924.0625 - val_mae: 909.9548 - val_mse: 855924.0625
Epoch 33/100
1/1 [==============================] - 0s 23ms/step - loss: 1263773.7500 - mae: 1109.2716 - mse: 1263773.7500 - val_loss: 855275.9375 - val_mae: 909.5978 - val_mse: 855275.9375
Epoch 34/100
1/1 [==============================] - 0s 24ms/step - loss: 1262996.0000 - mae: 1108.9205 - mse: 1262996.0000 - val_loss: 854619.0000 - val_mae: 909.2360 - val_mse: 854619.0000
Epoch 35/100
1/1 [==============================] - 0s 22ms/step - loss: 1262207.1250 - mae: 1108.5645 - mse: 1262207.1250 - val_loss: 853952.2500 - val_mae: 908.8683 - val_mse: 853952.2500
Epoch 36/100
1/1 [==============================] - 0s 23ms/step - loss: 1261406.1250 - mae: 1108.2029 - mse: 1261406.1250 - val_loss: 853275.5625 - val_mae: 908.4952 - val_mse: 853275.5625
Epoch 37/100
1/1 [==============================] - 0s 23ms/step - loss: 1260592.7500 - mae: 1107.8356 - mse: 1260592.7500 - val_loss: 852588.5625 - val_mae: 908.1162 - val_mse: 852588.5625
Epoch 38/100
1/1 [==============================] - 0s 23ms/step - loss: 1259767.3750 - mae: 1107.4626 - mse: 1259767.3750 - val_loss: 851891.7500 - val_mae: 907.7317 - val_mse: 851891.7500
Epoch 39/100
1/1 [==============================] - 0s 22ms/step - loss: 1258929.3750 - mae: 1107.0840 - mse: 1258929.3750 - val_loss: 851183.8750 - val_mae: 907.3408 - val_mse: 851183.8750
Epoch 40/100
1/1 [==============================] - 0s 22ms/step - loss: 1258078.6250 - mae: 1106.6993 - mse: 1258078.6250 - val_loss: 850465.5000 - val_mae: 906.9440 - val_mse: 850465.5000
Epoch 41/100
1/1 [==============================] - 0s 22ms/step - loss: 1257215.3750 - mae: 1106.3088 - mse: 1257215.3750 - val_loss: 849736.6875 - val_mae: 906.5413 - val_mse: 849736.6875
Epoch 42/100
1/1 [==============================] - 0s 22ms/step - loss: 1256338.8750 - mae: 1105.9122 - mse: 1256338.8750 - val_loss: 848997.0000 - val_mae: 906.1324 - val_mse: 848997.0000
Epoch 43/100
1/1 [==============================] - 0s 22ms/step - loss: 1255449.3750 - mae: 1105.5098 - mse: 1255449.3750 - val_loss: 848246.6250 - val_mae: 905.7173 - val_mse: 848246.6250
Epoch 44/100
1/1 [==============================] - 0s 23ms/step - loss: 1254546.6250 - mae: 1105.1012 - mse: 1254546.6250 - val_loss: 847485.5000 - val_mae: 905.2961 - val_mse: 847485.5000
Epoch 45/100
1/1 [==============================] - 0s 22ms/step - loss: 1253630.8750 - mae: 1104.6864 - mse: 1253630.8750 - val_loss: 846713.3750 - val_mae: 904.8688 - val_mse: 846713.3750
Epoch 46/100
1/1 [==============================] - 0s 21ms/step - loss: 1252702.0000 - mae: 1104.2655 - mse: 1252702.0000 - val_loss: 845930.6250 - val_mae: 904.4353 - val_mse: 845930.6250
Epoch 47/100
1/1 [==============================] - 0s 21ms/step - loss: 1251759.7500 - mae: 1103.8385 - mse: 1251759.7500 - val_loss: 845136.7500 - val_mae: 903.9954 - val_mse: 845136.7500
Epoch 48/100
1/1 [==============================] - 0s 22ms/step - loss: 1250804.2500 - mae: 1103.4052 - mse: 1250804.2500 - val_loss: 844331.8750 - val_mae: 903.5491 - val_mse: 844331.8750
Epoch 49/100
1/1 [==============================] - 0s 23ms/step - loss: 1249835.2500 - mae: 1102.9657 - mse: 1249835.2500 - val_loss: 843516.0625 - val_mae: 903.0966 - val_mse: 843516.0625
Epoch 50/100
1/1 [==============================] - 0s 22ms/step - loss: 1248852.7500 - mae: 1102.5200 - mse: 1248852.7500 - val_loss: 842689.0625 - val_mae: 902.6377 - val_mse: 842689.0625
Epoch 51/100
1/1 [==============================] - 0s 21ms/step - loss: 1247856.7500 - mae: 1102.0680 - mse: 1247856.7500 - val_loss: 841851.0000 - val_mae: 902.1725 - val_mse: 841851.0000
Epoch 52/100
1/1 [==============================] - 0s 21ms/step - loss: 1246847.5000 - mae: 1101.6095 - mse: 1246847.5000 - val_loss: 841001.7500 - val_mae: 901.7007 - val_mse: 841001.7500
Epoch 53/100
1/1 [==============================] - 0s 21ms/step - loss: 1245824.2500 - mae: 1101.1448 - mse: 1245824.2500 - val_loss: 840141.3750 - val_mae: 901.2225 - val_mse: 840141.3750
Epoch 54/100
1/1 [==============================] - 0s 22ms/step - loss: 1244787.5000 - mae: 1100.6736 - mse: 1244787.5000 - val_loss: 839269.5625 - val_mae: 900.7378 - val_mse: 839269.5625
Epoch 55/100
1/1 [==============================] - 0s 22ms/step - loss: 1243736.7500 - mae: 1100.1958 - mse: 1243736.7500 - val_loss: 838386.2500 - val_mae: 900.2463 - val_mse: 838386.2500
Epoch 56/100
1/1 [==============================] - 0s 21ms/step - loss: 1242672.0000 - mae: 1099.7115 - mse: 1242672.0000 - val_loss: 837491.5625 - val_mae: 899.7483 - val_mse: 837491.5625
Epoch 57/100
1/1 [==============================] - 0s 22ms/step - loss: 1241593.3750 - mae: 1099.2207 - mse: 1241593.3750 - val_loss: 836585.2500 - val_mae: 899.2435 - val_mse: 836585.2500
Epoch 58/100
1/1 [==============================] - 0s 23ms/step - loss: 1240500.5000 - mae: 1098.7231 - mse: 1240500.5000 - val_loss: 835667.3750 - val_mae: 898.7321 - val_mse: 835667.3750
Epoch 59/100
1/1 [==============================] - 0s 22ms/step - loss: 1239393.6250 - mae: 1098.2190 - mse: 1239393.6250 - val_loss: 834737.6875 - val_mae: 898.2136 - val_mse: 834737.6875
Epoch 60/100
1/1 [==============================] - 0s 22ms/step - loss: 1238272.2500 - mae: 1097.7081 - mse: 1238272.2500 - val_loss: 833796.1250 - val_mae: 897.6884 - val_mse: 833796.1250
Epoch 61/100
1/1 [==============================] - 0s 23ms/step - loss: 1237136.2500 - mae: 1097.1902 - mse: 1237136.2500 - val_loss: 832842.6250 - val_mae: 897.1560 - val_mse: 832842.6250
Epoch 62/100
1/1 [==============================] - 0s 23ms/step - loss: 1235985.7500 - mae: 1096.6654 - mse: 1235985.7500 - val_loss: 831877.2500 - val_mae: 896.6168 - val_mse: 831877.2500
Epoch 63/100
1/1 [==============================] - 0s 23ms/step - loss: 1234820.5000 - mae: 1096.1339 - mse: 1234820.5000 - val_loss: 830899.7500 - val_mae: 896.0704 - val_mse: 830899.7500
Epoch 64/100
1/1 [==============================] - 0s 22ms/step - loss: 1233640.7500 - mae: 1095.5952 - mse: 1233640.7500 - val_loss: 829910.0625 - val_mae: 895.5170 - val_mse: 829910.0625
Epoch 65/100
1/1 [==============================] - 0s 23ms/step - loss: 1232446.0000 - mae: 1095.0494 - mse: 1232446.0000 - val_loss: 828908.1250 - val_mae: 894.9563 - val_mse: 828908.1250
Epoch 66/100
1/1 [==============================] - 0s 21ms/step - loss: 1231236.2500 - mae: 1094.4967 - mse: 1231236.2500 - val_loss: 827894.1250 - val_mae: 894.3885 - val_mse: 827894.1250
Epoch 67/100
1/1 [==============================] - 0s 22ms/step - loss: 1230011.6250 - mae: 1093.9369 - mse: 1230011.6250 - val_loss: 826867.8750 - val_mae: 893.8135 - val_mse: 826867.8750
Epoch 68/100
1/1 [==============================] - 0s 22ms/step - loss: 1228772.0000 - mae: 1093.3698 - mse: 1228772.0000 - val_loss: 825829.5000 - val_mae: 893.2314 - val_mse: 825829.5000
Epoch 69/100
1/1 [==============================] - 0s 22ms/step - loss: 1227517.3750 - mae: 1092.7955 - mse: 1227517.3750 - val_loss: 824778.7500 - val_mae: 892.6419 - val_mse: 824778.7500
Epoch 70/100
1/1 [==============================] - 0s 22ms/step - loss: 1226247.7500 - mae: 1092.2142 - mse: 1226247.7500 - val_loss: 823715.7500 - val_mae: 892.0451 - val_mse: 823715.7500
Epoch 71/100
1/1 [==============================] - 0s 21ms/step - loss: 1224963.1250 - mae: 1091.6257 - mse: 1224963.1250 - val_loss: 822640.5000 - val_mae: 891.4411 - val_mse: 822640.5000
Epoch 72/100
1/1 [==============================] - 0s 23ms/step - loss: 1223663.3750 - mae: 1091.0299 - mse: 1223663.3750 - val_loss: 821552.8750 - val_mae: 890.8297 - val_mse: 821552.8750
Epoch 73/100
1/1 [==============================] - 0s 23ms/step - loss: 1222348.3750 - mae: 1090.4269 - mse: 1222348.3750 - val_loss: 820453.0000 - val_mae: 890.2110 - val_mse: 820453.0000
Epoch 74/100
1/1 [==============================] - 0s 22ms/step - loss: 1221018.3750 - mae: 1089.8165 - mse: 1221018.3750 - val_loss: 819340.8125 - val_mae: 889.5850 - val_mse: 819340.8125
Epoch 75/100
1/1 [==============================] - 0s 21ms/step - loss: 1219673.1250 - mae: 1089.1990 - mse: 1219673.1250 - val_loss: 818216.3125 - val_mae: 888.9514 - val_mse: 818216.3125
Epoch 76/100
1/1 [==============================] - 0s 22ms/step - loss: 1218312.6250 - mae: 1088.5740 - mse: 1218312.6250 - val_loss: 817079.3125 - val_mae: 888.3105 - val_mse: 817079.3125
Epoch 77/100
1/1 [==============================] - 0s 26ms/step - loss: 1216936.7500 - mae: 1087.9415 - mse: 1216936.7500 - val_loss: 815929.9375 - val_mae: 887.6622 - val_mse: 815929.9375
Epoch 78/100
1/1 [==============================] - 0s 25ms/step - loss: 1215545.8750 - mae: 1087.3018 - mse: 1215545.8750 - val_loss: 814768.1250 - val_mae: 887.0063 - val_mse: 814768.1250
Epoch 79/100
1/1 [==============================] - 0s 21ms/step - loss: 1214139.5000 - mae: 1086.6545 - mse: 1214139.5000 - val_loss: 813593.8125 - val_mae: 886.3429 - val_mse: 813593.8125
Epoch 80/100
1/1 [==============================] - 0s 23ms/step - loss: 1212717.6250 - mae: 1085.9999 - mse: 1212717.6250 - val_loss: 812407.0000 - val_mae: 885.6719 - val_mse: 812407.0000
Epoch 81/100
1/1 [==============================] - 0s 22ms/step - loss: 1211280.3750 - mae: 1085.3378 - mse: 1211280.3750 - val_loss: 811207.8125 - val_mae: 884.9933 - val_mse: 811207.8125
Epoch 82/100
1/1 [==============================] - 0s 21ms/step - loss: 1209827.7500 - mae: 1084.6681 - mse: 1209827.7500 - val_loss: 809995.9375 - val_mae: 884.3072 - val_mse: 809995.9375
Epoch 83/100
1/1 [==============================] - 0s 22ms/step - loss: 1208359.6250 - mae: 1083.9908 - mse: 1208359.6250 - val_loss: 808771.5000 - val_mae: 883.6133 - val_mse: 808771.5000
Epoch 84/100
1/1 [==============================] - 0s 21ms/step - loss: 1206876.0000 - mae: 1083.3062 - mse: 1206876.0000 - val_loss: 807534.5000 - val_mae: 882.9119 - val_mse: 807534.5000
Epoch 85/100
1/1 [==============================] - 0s 23ms/step - loss: 1205376.7500 - mae: 1082.6136 - mse: 1205376.7500 - val_loss: 806285.0625 - val_mae: 882.2026 - val_mse: 806285.0625
Epoch 86/100
1/1 [==============================] - 0s 23ms/step - loss: 1203862.0000 - mae: 1081.9136 - mse: 1203862.0000 - val_loss: 805022.7500 - val_mae: 881.4857 - val_mse: 805022.7500
Epoch 87/100

1/1 [==============================] - 0s 24ms/step - loss: 1202331.3750 - mae: 1081.2057 - mse: 1202331.3750 - val_loss: 803747.7500 - val_mae: 880.7609 - val_mse: 803747.7500
Epoch 88/100
1/1 [==============================] - 0s 22ms/step - loss: 1200785.2500 - mae: 1080.4902 - mse: 1200785.2500 - val_loss: 802460.1250 - val_mae: 880.0283 - val_mse: 802460.1250
Epoch 89/100
1/1 [==============================] - 0s 22ms/step - loss: 1199223.2500 - mae: 1079.7671 - mse: 1199223.2500 - val_loss: 801159.7500 - val_mae: 879.2878 - val_mse: 801159.7500
Epoch 90/100
1/1 [==============================] - 0s 22ms/step - loss: 1197645.6250 - mae: 1079.0359 - mse: 1197645.6250 - val_loss: 799846.6250 - val_mae: 878.5395 - val_mse: 799846.6250
Epoch 91/100
1/1 [==============================] - 0s 22ms/step - loss: 1196052.0000 - mae: 1078.2971 - mse: 1196052.0000 - val_loss: 798520.7500 - val_mae: 877.7832 - val_mse: 798520.7500
Epoch 92/100
1/1 [==============================] - 0s 22ms/step - loss: 1194442.6250 - mae: 1077.5504 - mse: 1194442.6250 - val_loss: 797182.2500 - val_mae: 877.0190 - val_mse: 797182.2500
Epoch 93/100
1/1 [==============================] - 0s 22ms/step - loss: 1192817.5000 - mae: 1076.7958 - mse: 1192817.5000 - val_loss: 795830.6250 - val_mae: 876.2468 - val_mse: 795830.6250
Epoch 94/100
1/1 [==============================] - 0s 22ms/step - loss: 1191176.3750 - mae: 1076.0333 - mse: 1191176.3750 - val_loss: 794466.3750 - val_mae: 875.4666 - val_mse: 794466.3750
Epoch 95/100
1/1 [==============================] - 0s 22ms/step - loss: 1189519.2500 - mae: 1075.2628 - mse: 1189519.2500 - val_loss: 793089.2500 - val_mae: 874.6783 - val_mse: 793089.2500
Epoch 96/100
1/1 [==============================] - 0s 22ms/step - loss: 1187846.1250 - mae: 1074.4843 - mse: 1187846.1250 - val_loss: 791699.1250 - val_mae: 873.8820 - val_mse: 791699.1250
Epoch 97/100
1/1 [==============================] - 0s 22ms/step - loss: 1186157.1250 - mae: 1073.6979 - mse: 1186157.1250 - val_loss: 790296.2500 - val_mae: 873.0775 - val_mse: 790296.2500
Epoch 98/100
1/1 [==============================] - 0s 22ms/step - loss: 1184451.7500 - mae: 1072.9032 - mse: 1184451.7500 - val_loss: 788880.3750 - val_mae: 872.2648 - val_mse: 788880.3750
Epoch 99/100
1/1 [==============================] - 0s 21ms/step - loss: 1182730.6250 - mae: 1072.1007 - mse: 1182730.6250 - val_loss: 787451.6250 - val_mae: 871.4440 - val_mse: 787451.6250
Epoch 100/100
1/1 [==============================] - 0s 22ms/step - loss: 1180993.2500 - mae: 1071.2898 - mse: 1180993.2500 - val_loss: 786009.8750 - val_mae: 870.6150 - val_mse: 786009.8750

In [35]:
loss, mae, mse = model.evaluate(X_test, y_test, verbose=2)
print("Testing set Mean Abs Error: {:5.2f} MPG".format(mae))

1/1 - 0s - loss: 1030114.1875 - mae: 986.8781 - mse: 1030114.1875 - 16ms/epoch - 16ms/step
Testing set Mean Abs Error: 986.88 MPG

In [42]:
import random
import math
lst = [random.random() for i in range(1000)]

In [59]:
data = {'tst':lst
        }
df = pd.DataFrame(data) 
tmp = df['tst']
values = tmp.values
train_data = values[:math.ceil(len(values)* 0.8)]
training_data_len = math.ceil(len(values)* 0.8)

In [60]:
x_train = []
y_train = []

for i in range(60, len(train_data)):
    x_train.append(train_data[i-60:i])
    y_train.append(train_data[i])
    
x_train, y_train = np.array(x_train), np.array(y_train)
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))

In [61]:
test_data = values[math.ceil(len(values)* 0.8)-60:]
x_test = []
y_test = values[training_data_len:]

for i in range(60, len(test_data)):
    x_test.append(test_data[i-60:i])

x_test = np.array(x_test)
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))

In [62]:
# if you really need lstm...
# https://medium.com/the-handbook-of-coding-in-finance/stock-prices-prediction-using-long-short-term-memory-lstm-model-in-python-734dd1ed6827

model = keras.Sequential()
model.add(layers.LSTM(100, return_sequences=True, input_shape=(x_train.shape[1], 1)))
model.add(layers.LSTM(100, return_sequences=False))
model.add(layers.Dense(25))
model.add(layers.Dense(1))
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm_4 (LSTM)               (None, 60, 100)           40800

 lstm_5 (LSTM)               (None, 100)               80400

 dense_13 (Dense)            (None, 25)                2525

 dense_14 (Dense)            (None, 1)                 26

=================================================================
Total params: 123,751
Trainable params: 123,751
Non-trainable params: 0
_________________________________________________________________

In [63]:
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(x_train, y_train, batch_size= 1, epochs=3)

Epoch 1/3
740/740 [==============================] - 9s 10ms/step - loss: 0.0926
Epoch 2/3
740/740 [==============================] - 7s 10ms/step - loss: 0.0882
Epoch 3/3
740/740 [==============================] - 8s 10ms/step - loss: 0.0874

In [65]:
predictions = model.predict(x_test)
rmse = np.sqrt(np.mean(predictions - y_test)**2)
rmse

7/7 [==============================] - 0s 9ms/step

0.05213242636788944

In [66]:
df = pd.read_csv('Investment_Data_Train.xlsx - train_data.csv')

In [68]:
pd.get_dummies(df)

,Unnamed: 0,Year,Amount,CO2 Emissions (Mmt),TotalNumberofInvestments,TotalAmountofAssistance,MSN_BDFDB,MSN_BDPRP,MSN_BFFDB,MSN_BFPRP,...,State_Tennessee,State_Texas,State_United States,State_Utah,State_Vermont,State_Virginia,State_Washington,State_West Virginia,State_Wisconsin,State_Wyoming
0,0,2015,21.000,35.027804,16.0,3345612.0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,2015,4.000,35.027804,16.0,3345612.0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,2015,21.000,35.027804,16.0,3345612.0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,3,2015,4.000,35.027804,16.0,3345612.0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,4,2015,17747.000,35.027804,16.0,3345612.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7590,7590,2019,5106671.000,NaN,NaN,NaN,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7591,7591,2019,5.698,NaN,NaN,NaN,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7592,7592,2019,25350.000,NaN,NaN,NaN,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7593,7593,2019,4449.000,NaN,NaN,NaN,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7594,7594,2019,25350.000,NaN,NaN,NaN,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [69]:
df = pd.read_csv('Investment_Data_Train.xlsx - train_data.csv')

In [77]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

X = df.apply(le.fit_transform)
X.head(100)

,Unnamed: 0,MSN,StateCode,Year,Amount,State,CO2 Emissions (Mmt),TotalNumberofInvestments,TotalAmountofAssistance
0,0,0,0,0,187,1,56,6,155
1,1,1,0,0,119,1,56,6,155
2,2,2,0,0,187,1,56,6,155
3,3,3,0,0,119,1,56,6,155
4,4,4,0,0,1930,1,56,6,155
...,...,...,...,...,...,...,...,...,...
95,95,8,3,0,1357,2,159,52,99
96,96,9,3,0,683,2,159,52,99
97,97,10,3,0,436,2,159,52,99
98,98,11,3,0,2673,2,159,52,99
99,99,12,3,0,3089,2,159,52,99

In [75]:
X['StateCode']

0        0
1        0
2        0
3        0
4        0
        ..
7590    52
7591    53
7592    53
7593    53
7594    53
Name: StateCode, Length: 7595, dtype: int32